### ISSUE TITLE
Alpha Vantage Crypto support

### ISSUE THREAD

**Issue by wayneconnolly** [FabioLuca/invst#3]
Hi - I saw you mentioned in the readme that AV api doesn't support crypto. I just read that it does.

https://www.alphavantage.co/documentation/#digital-currency

You can get all listings in https://www.alphavantage.co/digital_currency_list/ and all markets https://www.alphavantage.co/physical_currency_list/

**Comment by FabioLuca** [comment]
Thanks for the heads up. At the moment the focus shift to Yahoo Finance API, although the Alpha Vantage implementation is still available. The reason was on that Alpha Vantage Stock Time Series Daily Adjusted now is part of the Premium package, while Yahoo is still free. Yahoo have the Crypto support, however I've never tested it yet.

**Comment by wayneconnolly** [comment]
Ok, good to know. Thanks.
