### ISSUE TITLE
Store Data in Database

### ISSUE THREAD

**Issue by wayneconnolly** [FabioLuca/invst#4]
Storing the historic data and analysis in a database would be amazing. With your existing panda setup it should be straight forward?

Maybe also the ability to download and process all symbols in one go rather than having to do them as a single request.

**Comment by FabioLuca** [comment]
The actual implementation is storing into files (Microsoft Excel). So basically a new file stores the data for the given day. The decision in the past to use files instead of a database was because performance was not an issue, and the most important was that the final goal is to deploy / use from a cloud computing system, and to keep costs low, avoid the costs related to database usage. The first (current) implementation is using local files, but current goal is to store/load files directly from an online storage platform (e.g. Dropbox).

For the batch operation (multiple symbols) you can take the example from [automation/run_analysis.py ](https://github.com/FabioLuca/invst/blob/main/automation/run_analysis.py). If no argument is passed to the run_analysis function, it will process the analysis on the list defined inside it. Unfortunately much of the latest developments are still open, and so the documentation, so this option is not clear.

**Comment by wayneconnolly** [comment]
That makes sense. Thanks
